# Generated by Django 4.2.4 on 2023-08-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preview_pic',
            field=models.ImageField(blank=True, null=True, upload_to='project_pictures/'),
        ),
    ]
